Repository Move-Log/Move-Log-Android, pull requests merged in 2025-01, with the labels that each got.

#4 [MOV-22] 회원가입 & 로그인 + 카카오
  MoveLog/app/build.gradle.kts
  MoveLog/app/src/main/AndroidManifest.xml
  MoveLog/app/src/main/java/com/ilgusu/movelog/GlobalApplication.kt
  MoveLog/app/src/main/res/navigation/nav_graph.xml
  MoveLog/app/src/main/res/values-night/themes.xml
  MoveLog/app/src/main/res/values/themes.xml
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/AppNavigatorImpl.kt
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/NavigationCommand.kt
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/NavigationRoutes.kt
  MoveLog/data/build.gradle.kts
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/AuthRemoteDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/AuthRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/ClientModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/RepositoryModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/ServiceModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/OnlyMsgDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/auth/LoginRequestDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/auth/LoginResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/AuthRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/TokenRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/KakaoAuthService.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/auth/AuthService.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/AuthProvider.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/AuthRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/TokenRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/LoginUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/RefreshTokenUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/SignUpUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/SocialLoginUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/WithdrawUseCase.kt
  MoveLog/gradle/libs.versions.toml
  MoveLog/presentation/build.gradle.kts
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/util/UiState.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/signIn/SignInFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/signIn/SignInViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/term/TermsFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/term/TermsViewModel.kt
  MoveLog/presentation/src/main/res/drawable/bg_image_400_780.png
  MoveLog/presentation/src/main/res/drawable/ic_checkbox_selected.xml
  MoveLog/presentation/src/main/res/drawable/ic_checkbox_unselected.xml
  MoveLog/presentation/src/main/res/drawable/ic_google.xml
  MoveLog/presentation/src/main/res/drawable/ic_kakao.xml
  MoveLog/presentation/src/main/res/drawable/logo_symbol.xml
  MoveLog/presentation/src/main/res/drawable/logo_typeface.png
  MoveLog/presentation/src/main/res/drawable/selector_checkbox.xml
  MoveLog/presentation/src/main/res/drawable/shape_google_login.xml
  MoveLog/presentation/src/main/res/drawable/shape_kakao_login.xml
  MoveLog/presentation/src/main/res/drawable/shape_radius_8.xml
  MoveLog/presentation/src/main/res/layout/fragment_sign_in.xml
  MoveLog/presentation/src/main/res/layout/fragment_terms.xml
  MoveLog/presentation/src/main/res/values/strings.xml
  MoveLog/settings.gradle.kts
Labels: ✨ Feature

#5 [MOV-25] 홈 화면 작업
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/MyRecentNewsEntity.kt
  MoveLog/gradle/libs.versions.toml
  MoveLog/presentation/build.gradle.kts
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/RvMyRecentNewsAdapter.kt
  MoveLog/presentation/src/main/res/drawable/btn_round.xml
  MoveLog/presentation/src/main/res/drawable/ic_board.xml
  MoveLog/presentation/src/main/res/drawable/ic_logo.png
  MoveLog/presentation/src/main/res/drawable/ic_setting.png
  MoveLog/presentation/src/main/res/drawable/ic_stamp_blue.png
  MoveLog/presentation/src/main/res/drawable/ic_stamp_green.png
  MoveLog/presentation/src/main/res/drawable/ic_stamp_orange.png
  MoveLog/presentation/src/main/res/drawable/ic_stamp_purple.png
  MoveLog/presentation/src/main/res/drawable/ic_stamp_red.png
  MoveLog/presentation/src/main/res/drawable/ic_title_for_time.xml
  MoveLog/presentation/src/main/res/drawable/ic_wise_saying.xml
  MoveLog/presentation/src/main/res/layout/fragment_home.xml
  MoveLog/presentation/src/main/res/layout/item_my_recent_news_rv.xml
Labels: ✨ Feature

#6 [MOV-25] #2 홈화면 작업 & 설정 화면 작업
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/CircleIndicator.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/setting/SettingFragment.kt
  MoveLog/presentation/src/main/res/drawable/btn_record.xml
  MoveLog/presentation/src/main/res/drawable/ic_board.xml
  MoveLog/presentation/src/main/res/drawable/ic_do_disabled.png
  MoveLog/presentation/src/main/res/drawable/ic_do_enabled.png
  MoveLog/presentation/src/main/res/drawable/ic_eat_disabled.png
  MoveLog/presentation/src/main/res/drawable/ic_eat_enabled.png
  MoveLog/presentation/src/main/res/drawable/ic_go_disabled.png
  MoveLog/presentation/src/main/res/drawable/ic_go_enabled.png
  MoveLog/presentation/src/main/res/drawable/ic_left_arrow.png
  MoveLog/presentation/src/main/res/drawable/ic_right_arrow.png
  MoveLog/presentation/src/main/res/drawable/indicator_dot_off.xml
  MoveLog/presentation/src/main/res/drawable/indicator_dot_on.xml
  MoveLog/presentation/src/main/res/layout/fragment_home.xml
  MoveLog/presentation/src/main/res/layout/fragment_setting.xml
  MoveLog/presentation/src/main/res/layout/item_my_recent_news_rv.xml
  MoveLog/presentation/src/main/res/values/dimen.xml
  MoveLog/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#7 [MOV-50] 기록 기능 & 기록 확인 기능 & 네비게이션 모듈 개선
  MoveLog/app/src/main/AndroidManifest.xml
  MoveLog/app/src/main/res/navigation/nav_graph.xml
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/AppNavigatorImpl.kt
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/NavigationCommand.kt
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/NavigationRoutes.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/ClientModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/DataSourceModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/RepositoryModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/ServiceModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/BasicResponse.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/RecordRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/RecordService.kt
  MoveLog/data/src/main/java/com/ilgusu/data/util/AuthInterceptor.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/RecordRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/record/GetTodayRecordUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/record/RecordUseCase.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/custom/StepProgressView.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/util/DateUtil.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/util/ImageUtil.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordLastFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordLastViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/signIn/SignInFragment.kt
  MoveLog/presentation/src/main/res/drawable/ic_arrow.xml
  MoveLog/presentation/src/main/res/drawable/ic_close.xml
  MoveLog/presentation/src/main/res/drawable/ic_dash_line.png
  MoveLog/presentation/src/main/res/drawable/ic_foot_prints.xml
  MoveLog/presentation/src/main/res/drawable/ic_fork_knife.xml
  MoveLog/presentation/src/main/res/drawable/ic_hand_peace.xml
  MoveLog/presentation/src/main/res/drawable/ic_step.png
  MoveLog/presentation/src/main/res/drawable/ic_step_filled.png
  MoveLog/presentation/src/main/res/drawable/selector_word_input.xml
  MoveLog/presentation/src/main/res/drawable/shape_radius_8_with_stroke.xml
  MoveLog/presentation/src/main/res/drawable/shape_record_type_bg.xml
  MoveLog/presentation/src/main/res/layout/fragment_home.xml
  MoveLog/presentation/src/main/res/layout/fragment_record.xml
  MoveLog/presentation/src/main/res/layout/fragment_record_last.xml
  MoveLog/presentation/src/main/res/layout/view_today_board.xml
  MoveLog/presentation/src/main/res/navigation/nav_graph.xml
  MoveLog/presentation/src/main/res/values/font_style.xml
  MoveLog/presentation/src/main/res/values/strings.xml
Labels: 🔨 Refactor, ✨ Feature

#8 [MOV-FIX] 기록 화면 버그 픽스 & 홈 화면 시간 실시간 갱신 기능 구현
  MoveLog/data/src/main/java/com/ilgusu/data/util/AuthInterceptor.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordLastFragment.kt
  MoveLog/presentation/src/main/res/drawable/shape_radius_8_with_stroke.xml
  MoveLog/presentation/src/main/res/layout/fragment_record_last.xml
Labels: 🐞 BugFix, ✨ Feature

#9 [MOV-33] 회원탈퇴 기능 구현 & 비공개 테스트 설정
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/local/TokenLocalDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/local/TokenLocalDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/AuthRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/mapper/AuthMapper.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/TokenResponse.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/AuthRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/RecordRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/TokenRepositoryImpl.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/TokenPreferences.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/AuthRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/TokenRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/SaveTokenUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/SocialWithdrawUseCase.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/setting/SettingFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/setting/SettingViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/signIn/SignInViewModel.kt
Labels: 🚀 Deploy, ✨ Feature

#10 [MOV-FIX] Kakao Login Context 문제 수정
  MoveLog/data/src/main/java/com/ilgusu/data/di/ServiceModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/AuthRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/KakaoAuthService.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/AuthRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/auth/SocialLoginUseCase.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/signIn/SignInFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/signIn/SignInViewModel.kt
Labels: 🐞 BugFix

#11 [MOV-000] News & Record APIs 추가 및 UseCase 작성
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/NewsRemoteDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/NewsRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/DataSourceModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/RepositoryModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/di/ServiceModule.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/BasicResponse.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/CreateNewsHeadLineRequestDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/CreateNewsHeadLineResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/GetDateNewsRecordResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/GetRecentRecordImageDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/GetTodayNewsRecordResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/GetWeekNewsRecordResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/NewsContentDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/RecommendNewsKeywordResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/news/SearchRecordDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/record/TodayRecordResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/NewsRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/RecordRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/NewsService.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/RecordService.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/enum/RecordOption.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/Pageable.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/news/ImageInfo.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/news/NewsContent.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/news/RecommendKeyword.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/NewsRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/RecordRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/news/CreateNewsHeadLinesUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/news/GetDateNewsRecordUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/news/GetTodayNewsRecordUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/news/GetWeekNewsRecordUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/news/PostNewsUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/news/RecommendNewsKeywordsUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/record/GetRecentRecordImagesUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/record/RecordUseCase.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/record/SearchRecordUseCase.kt
Labels: 📬 API

#12 [MOV-25 #2] 날짜별 기록 조회 화면
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/CalendarFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/CalendarViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/DayAdapter.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/MonthAdapter.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/setting/SettingFragment.kt
  MoveLog/presentation/src/main/res/drawable/bg_calendar.xml
  MoveLog/presentation/src/main/res/drawable/ic_selected_date.png
  MoveLog/presentation/src/main/res/drawable/ic_vector_left.png
  MoveLog/presentation/src/main/res/drawable/ic_vector_right.png
  MoveLog/presentation/src/main/res/layout/fragment_calendar.xml
  MoveLog/presentation/src/main/res/layout/fragment_home.xml
  MoveLog/presentation/src/main/res/layout/item_day.xml
  MoveLog/presentation/src/main/res/layout/item_month.xml
  MoveLog/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#13 [MOV-25-#3] 날짜별 기록 목록 조회 API 적용
  MoveLog/core/navigation/src/main/java/com/ilgusu/navigation/NavigationRoutes.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/NewsRemoteDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/NewsRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSource.kt
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSourceImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/record/GetDateRecordCalendarResponseDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/model/record/RecordCalendarContentDTO.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/AuthRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/repository/RecordRepositoryImpl.kt
  MoveLog/data/src/main/java/com/ilgusu/data/service/RecordService.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/RecordCalendarContent.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/repository/RecordRepository.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/usecase/record/GetTodayRecordListUseCase.kt
  MoveLog/presentation/build.gradle.kts
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/CalendarFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/CalendarViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/MonthAdapter.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/RecordRvAdapter.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/home/HomeViewModel.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/setting/SettingFragment.kt
  MoveLog/presentation/src/main/res/drawable/bg_calendar.xml
  MoveLog/presentation/src/main/res/drawable/ic_dots.png
  MoveLog/presentation/src/main/res/drawable/ic_radio_button.png
  MoveLog/presentation/src/main/res/drawable/shape_chip_disable.xml
  MoveLog/presentation/src/main/res/layout/fragment_calendar.xml
  MoveLog/presentation/src/main/res/layout/item_day.xml
  MoveLog/presentation/src/main/res/layout/item_recorded_news.xml
  MoveLog/presentation/src/main/res/navigation/nav_graph.xml
  MoveLog/presentation/src/main/res/values/strings.xml
Labels: 📬 API, ✨ Feature

#15 [MOV-74] 1.0.0 배포 준비
  MoveLog/app/src/main/AndroidManifest.xml
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/CalendarFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/news/create/NewsCreateFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/news/recent/NewsFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/news/recent/NewsRecentRvAdapter.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/news/result/NewsResultFragment.kt
  MoveLog/presentation/src/main/res/layout/fragment_news.xml
  MoveLog/presentation/src/main/res/layout/item_recent_news_default.xml
  MoveLog/presentation/src/main/res/layout/item_recent_news_first.xml
  MoveLog/presentation/src/main/res/layout/view_bottom_nav.xml
Labels: 🐞 BugFix, ✨ Feature

#16 [MOV-29] 뉴스 이미지 공유 기능 구현
  MoveLog/app/src/main/AndroidManifest.xml
  MoveLog/app/src/main/res/xml/file_paths.xml
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/news/create/NewsCreateFragment.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/news/result/NewsResultFragment.kt
  MoveLog/presentation/src/main/res/drawable/ic_instagram.xml
  MoveLog/presentation/src/main/res/layout/fragment_news_result.xml
  MoveLog/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#17 [MOV-76] 기록 추가 시 이미지 선택 사항으로 수정
  MoveLog/data/src/main/java/com/ilgusu/data/datasource/remote/RecordRemoteDataSourceImpl.kt
  MoveLog/domain/src/main/java/com/ilgusu/domain/model/RecordCalendarContent.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/calendar/RecordRvAdapter.kt
  MoveLog/presentation/src/main/java/com/ilgusu/presentation/view/record/RecordLastFragment.kt
  MoveLog/presentation/src/main/res/layout/item_recorded_news.xml
Labels: ✨ Feature
